.template 0
###############################################################################
# Copyright (c) 2014-2015 libbitcoin developers (see COPYING).
#
# GSL generate libbitcoin travis.yml.
#
# This is a code generator built using the iMatix GSL code generation
# language. See https://github.com/imatix/gsl for details.
###############################################################################
# Functions
###############################################################################

function apt_get(name, system)
    define my.get = ""
    if (my.system = "osx")
        my.get = "brew unlink $(my.name); brew install $(my.name)"
    elsif (my.system = "linux")
        my.get = "sudo apt-get -qq install $(my.name)"
    else
        abort "Invalid system type for get package: $(my.name)."
    endif
    return my.get
endfunction

# We must do this because lcov is uses exclusions only.
function job_coverage_exclusions(job, repository)
    define my.job = job_coverage_exclusions.job
    define my.repository = job_coverage_exclusions.repository
    
    # Exclude all system directories.
    define my.excludes = quote("/usr/*")
    
    # Exclude the prefix directory (absolute).
    define my.prefix = job_option(my.job, "prefix")?
    if (!is_empty(my.prefix))
        my.excludes += " $(quote("$(my.prefix)/*"))"
    endif
    
    # Exclude the build-dir directory (relative to main target).
    define my.build_dir = job_option(my.job, "build-dir")?
    if (is_empty(my.build_dir))
        define my.library = my.repository.name
        my.excludes += " $(quote("build-$(my.library)/*"))"
    else
        my.excludes += " $(quote("$(my.build_dir)/*"))"
    endif
    
    # Exclude directories of cpp products that are not installed (relative).
    define my.make = my.repository->make?
    if (defined(my.make))
        for my.make.product as _product where is_not_covered(_product)
            my.excludes += " $(quote("$(_product.path)/*"))"
        endfor _product
    endif
    
    # Exclude explicitly-specified paths.
    for my.job.exclude as _exclude
        my.excludes += " $(quote(_exclude.path))"
    endfor _exclude    
    
    return my.excludes
endfunction

function job_title(job)
    define my.job = job_title.job
    return "$(my.job.system)/$(my.job.compiler)/$(my.job.link)"
endfunction

function job_options(job)
    define my.job = job_options.job
    define my.job_options = ""
    for my.job.option as _option
        my.job_options += " $(_option.value)"
    endfor _option
    return trim_left(my.job_options)
endfunction

function job_install(job)
    define my.job = job_install.job
    define my.sudo = is_true(my.job.sudo) ?? "sudo CXX=$CXX CC=$CC " ? ""
    return "$(my.sudo)./install.sh $(job_options(my.job))"
endfunction

function job_predicate_link(job)
    define my.job = job_predicate_link.job
    return "$$(my.job.link:upper,c%-7s)"
endfunction

function job_predicate_system(job)
    define my.job = job_predicate.job
    return "$$(my.job.system:upper,c%-5s)"
endfunction

function job_predicate_compiler(job)
    define my.job = job_predicate_compiler.job
    return "$$(my.job.compiler:upper,c%-5s)"
endfunction

function job_predicate_platform(job)
    define my.job = job_predicate_platform.job
    return "$(job_predicate_system(my.job)) && $(job_predicate_compiler(my.job))"
endfunction

function job_predicate(job)
    define my.job = job_predicate.job
    return "$(job_predicate_platform(my.job)) && $(job_predicate_link(my.job))"
endfunction

function condition(predicate)
    return "if [[ $(my.predicate) ]]; then"
endfunction

###############################################################################
# Macros
###############################################################################
.endtemplate
.template 1
.
.macro initialize_matrix(matrix)
.   define my.matrix = initialize_matrix.matrix
os:
.   # TODO: enumerate from matrixes.
    - osx
    - linux
    
compiler:
.   # TODO: enumerate from matrixes.
    - clang
    - gcc
    
env:
.   # TODO: enumerate from matrixes.
    - LINK=static
    - LINK=dynamic

.   # TODO: enumerate from matrixes.
matrix:
    exclude:
        - os: osx
          compiler: gcc
    fast_finish:
        - true

.endmacro #initialize_matrix
.
.macro set_aliases(matrix)
.   define my.matrix = set_aliases.matrix
    # Set aliases for readability.
    - $(condition("$CC             == gcc    ")) GCC=true; fi
    - $(condition("$CC             == clang  ")) CLANG=true; fi
    - $(condition("$LINK           == static ")) STATIC=true; fi
    - $(condition("$LINK           == dynamic")) DYNAMIC=true; fi
    - $(condition("$TRAVIS_OS_NAME == osx    ")) OSX=true; fi
    - $(condition("$TRAVIS_OS_NAME == linux  ")) LINUX=true; fi

.endmacro #set_aliases
.
.macro set_repositories(matrix)
.   define my.matrix = set_repositories.matrix
.   define my.linux       = condition("$LINUX          ")
.   define my.linux_clang = condition("$LINUX && $CLANG")
.
    # Set package repository.
    - $(my.linux) sudo add-apt-repository -y ppa:boost-latest/ppa; fi
    - $(my.linux) sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
    - $(my.linux_clang) sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

    # Update the system.
    - $(my.linux) sudo apt-get -qq update; fi

.endmacro #set_repositories
.
.macro install_compilers(matrix)
.   define my.matrix = install_compilers.matrix
.   define my.linux       = condition("$LINUX          ")
.   define my.linux_clang = condition("$LINUX && $CLANG")
.
    # Install g++ 4.8
    - $(my.linux) sudo apt-get install -qq g++-4.8 --allow-unauthenticated; fi
    - $(my.linux) sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
    - $(my.linux) sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50; fi
    - $(my.linux) sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 50; fi

    # Install clang++ 3.4
    - $(my.linux_clang) sudo apt-get install -qq clang-3.4 --allow-unauthenticated; fi
    - $(my.linux_clang) sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.4 50; fi
    - $(my.linux_clang) sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.4 50; fi

.endmacro #install_compilers
.
.# The --build-dir install.sh option is not supported by this code coverage tool.
.macro code_coverage(repository)
.   define my.repository = code_coverage.repository
.   define my.job = matrix_converage_job(my.repository->matrix)?
.   if (defined(my.job))
.       define my.linux_gcc_static = condition("$LINUX && $GCC   && $STATIC ")
.       define my.exclusions = job_coverage_exclusions(my.job, my.repository)
.
    # Install coveralls and current lcov.
    - $(my.linux_gcc_static) wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz; fi
    - $(my.linux_gcc_static) tar xf lcov_1.11.orig.tar.gz; fi
    - $(my.linux_gcc_static) sudo make -C lcov-1.11 install; fi
    - $(my.linux_gcc_static) gem install coveralls-lcov; fi

    # Capture coverage info, filter out system and test code, and debug before upload.
    - $(my.linux_gcc_static) lcov --directory . --capture --output-file coverage.info; fi
    - $(my.linux_gcc_static) lcov --remove coverage.info $(my.exclusions) --output-file coverage.info; fi
    - $(my.linux_gcc_static) lcov --list coverage.info; fi
    
    # Upload coverage info to coveralls service (--repo-token <private coveralls repo token>).
    - $(my.linux_gcc_static) coveralls-lcov coverage.info; fi
.
.   endif
.endmacro #code_coverage
.
.macro install_packages(matrix, system)
.   define my.matrix = install_packages.matrix
.   for my.matrix.job as _job where count(_job.get) > 0
    # Download and install packages for $(job_title(_job)).
.       for _job.get as _get
    - $(condition(job_predicate(_job))) $(apt_get(_get.name, system)); fi
.       endfor _get

.   endfor _job
.endmacro #install_packages
.
.macro run_script(matrix)
.   define my.matrix = run_script.matrix
    # Download and build $(_repository.name) and all dependencies.
.   for my.matrix.job as _job
    - $(condition(job_predicate(_job))) $(job_install(_job)); fi
.   endfor _job

.endmacro #run_script
.
.endtemplate
.template 0
###############################################################################
# Generation
###############################################################################
.endtemplate
.template 1
.macro generate_travisyml()
.for generate.repository by name as _repository
.   require(_repository, "repository", "name")
.   create_directory(_repository.name)
.   define my.out_file = "$(_repository.name)/.travis.yml"
.   notify(my.out_file)
.   output(my.out_file)
.   copyleft(_repository.name)
.   define my.matrix = _repository->matrix

language:
    - cpp

.   initialize_matrix(my.matrix)
before_install:

.   set_aliases(my.matrix)
.   set_repositories(my.matrix)
install:

.   install_compilers(my.matrix)
.   install_packages(my.matrix)
script:

.   run_script(my.matrix)
after_success:

.   code_coverage(_repository)
.
.   close
.endfor _repository
.endmacro # generate_travisyml
.endtemplate